 
// Type: Aptusoft.VentaGeneral
 
 
// version 1.8.0

using MySql.Data.MySqlClient;
using System.Data;
using System.Data.Common;

namespace Aptusoft
{
  internal class VentaGeneral
  {
    private Conexion conexion = Conexion.getConecta();

    public DataTable cierreDiaInforme(string filtro)
    {
      string str1 = "SELECT 'BOLETA' as tipoDocumentoVenta, '1-VENTA' as tipo,  folio, fechaEmision,  medioPago,    totalaCobrar as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM boletas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND tipoDocumento='BOLETA' ORDER BY folio";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT 'VOUCHER' as tipoDocumentoVenta, '1-VENTA' as tipo,  numeroVoucher as 'folio', fechaEmision,  medioPago,    totalaCobrar as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM boletas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND tipoDocumento='VOUCHER' ORDER BY idBoleta";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str3 = "SELECT 'BOLETA FISCAL' as tipoDocumentoVenta, '1-VENTA' as tipo,  folio, fechaEmision,  medioPago,    totalaCobrar as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM boletasfiscal \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str4 = "SELECT 'FACTURA' as tipoDocumentoVenta, '1-VENTA' as tipo,  folio,   fechaEmision, medioPago,    total as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM facturas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str4;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str5 = "SELECT 'FACTURA EXENTA' as tipoDocumentoVenta, '1-VENTA' as tipo,  folio,   fechaEmision, medioPago,    total as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM facturasexentas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str5;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str6 = "SELECT 'FACTURA ELECTRONICA' as tipoDocumentoVenta, '1-VENTA' as tipo,  folio,   fechaEmision, medioPago,    total as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM electronica_factura \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str6;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str7 = "SELECT 'BOLETA ELECTRONICA' as tipoDocumentoVenta, '1-VENTA' as tipo,  folio,   fechaEmision, medioPago,    total as totalDocumentoVenta, totalPagado, totalDocumentado, totalPendiente, caja    \r\n FROM electronica_boleta \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str7;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str8 = "SELECT 'CAJA' as tipoDocumentoVenta, '2-CAJA' as tipo,  idControlCaja as 'folio',   fechaIngreso as 'fechaEmision', tipoAccion as 'medioPago',    monto as totalDocumentoVenta,  monto as totalPagado,  caja    \r\n FROM controlcaja \r\n WHERE " + filtro.Replace("fechaEmision", "fechaIngreso") + " ORDER BY idControlCaja";
      ((DbCommand) command).CommandText = str8;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }

    public DataTable boletaFacturaInforme(string filtro)
    {
      string str1 = "SELECT 'BOLETA' as tipoDocumentoVenta,    folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial, direccion, comuna, ciudad, giro, fono, fax, contacto, diasPlazo, idMedioPago, medioPago, idVendedor, vendedor, idCentroCosto, centroCosto, ordenCompra, subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total, totalExento, totalaCobrar, totalPalabras, estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente, impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, porcentajeImpuesto2, porcentajeImpuesto1, porcentajeImpuesto3, porcentajeImpuesto4, porcentajeImpuesto5, comisionVendedor, caja    \r\n FROM boletas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT 'FACTURA' as tipoDocumentoVenta,  idFactura, folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial, direccion, comuna, ciudad, giro, fono, fax, contacto, diasPlazo, idMedioPago, medioPago, idVendedor, vendedor, idCentroCosto, centroCosto, ordenCompra, subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total, '0' as 'totalExento', '0' as 'totalaCobrar', totalPalabras, estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente, impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, porcentajeImpuesto2, porcentajeImpuesto1, porcentajeImpuesto3, porcentajeImpuesto4, porcentajeImpuesto5, comisionVendedor, caja    \r\n FROM facturas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str3 = "SELECT 'NOTA CREDITO' as tipoDocumentoVenta,    idNotaCredito as 'idFactura', folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial, direccion, comuna, ciudad, giro, fono, fax, contacto, diasPlazo, idMedioPago, medioPago, idVendedor, vendedor, idCentroCosto, centroCosto, subtotal * -1 as 'subtotal', porcentajeDescuento, descuento * -1 as 'descuento', porcentajeIva, iva * -1 as 'iva', neto * -1 as 'neto', total * -1 as 'total', '0' as 'totalExento', '0' as 'totalaCobrar',   impuesto1 * -1 as 'impuesto1', impuesto2 * -1 as 'impuesto2', impuesto3 * -1 as 'impuesto3', impuesto4 * -1 as 'impuesto4', impuesto5 * -1 as 'impuesto5',    porcentajeImpuesto1, porcentajeImpuesto2, porcentajeImpuesto3, porcentajeImpuesto4, porcentajeImpuesto5,      comisionVendedor,    caja    \r\n FROM notacredito \r\n WHERE idTipo=3 AND " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str4 = "SELECT 'BOLETA FISCAL' as tipoDocumentoVenta,    folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial, direccion, comuna, ciudad, giro, fono, fax, contacto, diasPlazo, idMedioPago, medioPago, idVendedor, vendedor, idCentroCosto, centroCosto, ordenCompra, subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total, totalExento, totalaCobrar, totalPalabras, estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente, impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, porcentajeImpuesto2, porcentajeImpuesto1, porcentajeImpuesto3, porcentajeImpuesto4, porcentajeImpuesto5, comisionVendedor, caja    \r\n FROM boletasfiscal \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str4;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }


    public DataTable boletaFacturaInformeDetalle(string filtro)
    {
 string filtro1 = "facturas." + filtro;
 string filtro2 = "boletas." + filtro;
 string filtro3 = "boletasfiscal." + filtro;
      string str1 = "SELECT 'FACTURA' as tipoDocumentoVenta, facturas.idFactura, facturas.folio, facturas.fechaEmision, facturas.fechaVencimiento, facturas.idCliente, facturas.rut, facturas.digito, facturas.razonSocial, facturas.direccion, facturas.comuna, facturas.ciudad, facturas.giro, facturas.fono, facturas.fax, facturas.contacto, facturas.diasPlazo, facturas.idMedioPago, facturas.medioPago, facturas.idVendedor,  facturas.vendedor, facturas.comisionVendedor, facturas.idCentroCosto,  facturas.centroCosto,  facturas.ordenCompra,  facturas.subtotal,  facturas.porcentajeDescuento, facturas.descuento,  facturas.porcentajeIva,  facturas.iva, facturas.neto,  facturas.total,  facturas.totalPalabras,  facturas.estadoPago,  facturas.estadoDocumento,  facturas.impuesto1, facturas.impuesto2, facturas.impuesto3, facturas.impuesto4, facturas.impuesto5, facturas.porcentajeImpuesto1, facturas.porcentajeImpuesto2, facturas.porcentajeImpuesto3, facturas.porcentajeImpuesto4, facturas.porcentajeImpuesto5, detallefactura.idFacturaLinea, detallefactura.folioFactura, detallefactura.fechaIngreso, detallefactura.codigo, detallefactura.descripcion, detallefactura.valorVenta, detallefactura.cantidad, detallefactura.porcentajeDescuentoLinea, detallefactura.descuentoLinea, detallefactura.subtotalLinea,  detallefactura.totalLinea,  detallefactura.tipoDescuento,  detallefactura.listaPrecio,  detallefactura.bodega,  detallefactura.idDetallefactura, detallefactura.idImpuesto,  detallefactura.netoLinea, detallefactura.valorCompra, clientes.rubro\r\n FROM facturas INNER JOIN detallefactura \r\n ON facturas.idFactura = detallefactura.idFacturaLinea\r\n INNER JOIN clientes\r\n ON clientes.codigo=facturas.idCliente \r\n WHERE " + filtro1 + " ORDER BY facturas.folio";
      DataTable boletaFacturaInformeDetalle = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter)new MySqlDataAdapter(command)).Fill(boletaFacturaInformeDetalle);
      string str2 = "SELECT 'FACTURA ELECTRONICA' as tipoDocumentoVenta, facturas.idFactura, facturas.folio, facturas.fechaEmision, facturas.fechaVencimiento, facturas.idCliente,  facturas.rut,  facturas.digito,  facturas.razonSocial, facturas.direccion,  facturas.comuna,  facturas.ciudad,  facturas.giro,  facturas.fono,  facturas.fax,  facturas.contacto,  facturas.diasPlazo,  facturas.idMedioPago, facturas.medioPago,  facturas.idVendedor,  facturas.vendedor, facturas.comisionVendedor,  facturas.idCentroCosto,  facturas.centroCosto,  facturas.ordenCompra,  facturas.subtotal,  facturas.porcentajeDescuento, facturas.descuento,  facturas.porcentajeIva,  facturas.iva, facturas.neto,  facturas.total,  facturas.totalPalabras,  facturas.estadoPago,  facturas.estadoDocumento,  facturas.impuesto1, facturas.impuesto2, facturas.impuesto3, facturas.impuesto4, facturas.impuesto5, facturas.porcentajeImpuesto1, facturas.porcentajeImpuesto2, facturas.porcentajeImpuesto3, facturas.porcentajeImpuesto4, facturas.porcentajeImpuesto5, detallefactura.idFacturaLinea, detallefactura.folioFactura, detallefactura.fechaIngreso, detallefactura.codigo, detallefactura.descripcion, detallefactura.valorVenta, detallefactura.cantidad, detallefactura.porcentajeDescuentoLinea, detallefactura.descuentoLinea, detallefactura.subtotalLinea,  detallefactura.totalLinea,  detallefactura.tipoDescuento,  detallefactura.listaPrecio,  detallefactura.bodega,  detallefactura.idDetallefactura, detallefactura.idImpuesto,  detallefactura.netoLinea, detallefactura.valorCompra, clientes.rubro\r\n FROM electronica_factura facturas INNER JOIN electronica_detalle_factura detallefactura\r\n ON facturas.idFactura = detallefactura.idFacturaLinea\r\n INNER JOIN clientes\r\n ON clientes.codigo=facturas.idCliente \r\n WHERE " + filtro1 + " ORDER BY facturas.folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter)new MySqlDataAdapter(command)).Fill(boletaFacturaInformeDetalle);
      string str3 = "SELECT  'BOLETA' as tipoDocumentoVenta, boletas.idBoleta, boletas.folio, boletas.fechaEmision, boletas.fechaVencimiento, boletas.dia, boletas.mes, boletas.ano, boletas.idCliente,  boletas.rut,  boletas.digito,  boletas.razonSocial, boletas.direccion,  boletas.comuna,  boletas.ciudad,  boletas.giro,  boletas.fono,  boletas.fax,  boletas.contacto,  boletas.diasPlazo,  boletas.idMedioPago, boletas.medioPago,  boletas.idVendedor,  boletas.vendedor,  boletas.idCentroCosto,  boletas.centroCosto,  boletas.ordenCompra,  boletas.subtotal,  boletas.porcentajeDescuento, boletas.descuento,  boletas.porcentajeIva,  boletas.iva, boletas.neto,  boletas.total,  boletas.totalExento, boletas.totalaCobrar, boletas.totalPalabras,  boletas.estadoPago,  boletas.estadoDocumento, boletas.totalPagado, boletas.totalDocumentado, boletas.totalPendiente, boletas.pagaCon, boletas.vuelto,    boletas.impuesto1, boletas.impuesto2, boletas.impuesto3, boletas.impuesto4, boletas.impuesto5, boletas.porcentajeImpuesto1, boletas.porcentajeImpuesto2, boletas.porcentajeImpuesto3, boletas.porcentajeImpuesto4, boletas.porcentajeImpuesto5, boletas.comisionVendedor, boletas.idTicket, boletas.folioTicket, boletas.caja, boletas.idCotizacion, boletas.folioCotizacion, detalleboleta.idDetalleboleta,    detalleboleta.idBoletaLinea, detalleboleta.folioBoleta, detalleboleta.fechaIngreso, detalleboleta.codigo, detalleboleta.descripcion, detalleboleta.valorVenta, detalleboleta.cantidad, detalleboleta.porcentajeDescuentoLinea, detalleboleta.descuentoLinea, detalleboleta.subtotalLinea,  detalleboleta.totalLinea,  detalleboleta.tipoDescuento,  detalleboleta.listaPrecio,  detalleboleta.bodega,  detalleboleta.exento,  detalleboleta.idImpuesto,  detalleboleta.netoLinea, detalleboleta.valorCompra, clientes.rubro\r\n    FROM boletas INNER JOIN detalleboleta \r\n    ON boletas.idBoleta = detalleboleta.idBoletaLinea    \r\n    LEFT JOIN clientes\r\n    ON clientes.codigo=boletas.idCliente \r\n    WHERE " + filtro2 + " ORDER BY folio";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter)new MySqlDataAdapter(command)).Fill(boletaFacturaInformeDetalle);
      string str4 = "SELECT  'BOLETA FISCAL' as tipoDocumentoVenta, boletasfiscal.idBoleta, boletasfiscal.folio, boletasfiscal.fechaEmision, boletasfiscal.fechaVencimiento, boletasfiscal.dia, boletasfiscal.mes, boletasfiscal.ano, boletasfiscal.idCliente,  boletasfiscal.rut,  boletasfiscal.digito,  boletasfiscal.razonSocial, boletasfiscal.direccion,  boletasfiscal.comuna,  boletasfiscal.ciudad,  boletasfiscal.giro,  boletasfiscal.fono,  boletasfiscal.fax,  boletasfiscal.contacto,  boletasfiscal.diasPlazo,  boletasfiscal.idMedioPago, boletasfiscal.medioPago,  boletasfiscal.idVendedor,  boletasfiscal.vendedor,  boletasfiscal.idCentroCosto,  boletasfiscal.centroCosto,  boletasfiscal.ordenCompra,  boletasfiscal.subtotal,  boletasfiscal.porcentajeDescuento, boletasfiscal.descuento,  boletasfiscal.porcentajeIva,  boletasfiscal.iva, boletasfiscal.neto,  boletasfiscal.total,  boletasfiscal.totalExento, boletasfiscal.totalaCobrar, boletasfiscal.totalPalabras,  boletasfiscal.estadoPago,  boletasfiscal.estadoDocumento, boletasfiscal.totalPagado, boletasfiscal.totalDocumentado, boletasfiscal.totalPendiente, boletasfiscal.pagaCon, boletasfiscal.vuelto,    boletasfiscal.impuesto1, boletasfiscal.impuesto2, boletasfiscal.impuesto3, boletasfiscal.impuesto4, boletasfiscal.impuesto5, boletasfiscal.porcentajeImpuesto1, boletasfiscal.porcentajeImpuesto2, boletasfiscal.porcentajeImpuesto3, boletasfiscal.porcentajeImpuesto4, boletasfiscal.porcentajeImpuesto5, boletasfiscal.comisionVendedor, boletasfiscal.idTicket, boletasfiscal.folioTicket, boletasfiscal.caja, boletasfiscal.idCotizacion, boletasfiscal.folioCotizacion, detalleboletafiscal.idDetalleboleta,    detalleboletafiscal.idBoletaLinea, detalleboletafiscal.folioBoleta, detalleboletafiscal.fechaIngreso, detalleboletafiscal.codigo, detalleboletafiscal.descripcion, detalleboletafiscal.valorVenta, detalleboletafiscal.cantidad, detalleboletafiscal.porcentajeDescuentoLinea, detalleboletafiscal.descuentoLinea, detalleboletafiscal.subtotalLinea,  detalleboletafiscal.totalLinea,  detalleboletafiscal.tipoDescuento,  detalleboletafiscal.listaPrecio,  detalleboletafiscal.bodega,  detalleboletafiscal.exento,  detalleboletafiscal.idImpuesto,  detalleboletafiscal.netoLinea, detalleboletafiscal.valorCompra, clientes.rubro\r\n    FROM boletasfiscal INNER JOIN detalleboletafiscal \r\n    ON boletasfiscal.idBoleta = detalleboletafiscal.idBoletaLinea \r\n    LEFT JOIN clientes\r\n    ON clientes.codigo=boletasfiscal.idCliente \r\n    WHERE " + filtro3 + " ORDER BY folio";
      ((DbCommand) command).CommandText = str4;
      ((DbDataAdapter)new MySqlDataAdapter(command)).Fill(boletaFacturaInformeDetalle);
      string str5 = "SELECT  'BOLETA ELECTRONICA' as tipoDocumentoVenta, facturas.idBoleta, facturas.folio, facturas.fechaEmision, facturas.fechaVencimiento, facturas.idCliente,  facturas.rut,  facturas.digito,  facturas.razonSocial, facturas.direccion,  facturas.comuna,  facturas.ciudad,  facturas.giro,  facturas.fono,  facturas.fax,  facturas.contacto,  facturas.diasPlazo,  facturas.idMedioPago, facturas.medioPago,  facturas.idVendedor,  facturas.vendedor, facturas.comisionVendedor,  facturas.idCentroCosto,  facturas.centroCosto,  facturas.ordenCompra,  facturas.subtotal,  facturas.porcentajeDescuento, facturas.descuento,  facturas.porcentajeIva,  facturas.iva, facturas.neto,  facturas.total,  facturas.totalPalabras,  facturas.estadoPago,  facturas.estadoDocumento,  facturas.impuesto1, facturas.impuesto2, facturas.impuesto3, facturas.impuesto4, facturas.impuesto5, facturas.porcentajeImpuesto1, facturas.porcentajeImpuesto2, facturas.porcentajeImpuesto3, facturas.porcentajeImpuesto4, facturas.porcentajeImpuesto5, detallefactura.idBoletaLinea, detallefactura.folioBoleta, detallefactura.fechaIngreso, detallefactura.codigo, detallefactura.descripcion, detallefactura.valorVenta, detallefactura.cantidad, detallefactura.porcentajeDescuentoLinea, detallefactura.descuentoLinea, detallefactura.subtotalLinea,  detallefactura.totalLinea,  detallefactura.tipoDescuento,  detallefactura.listaPrecio,  detallefactura.bodega,  detallefactura.idDetalleBoleta, detallefactura.idImpuesto,  detallefactura.netoLinea, detallefactura.valorCompra, clientes.rubro\r\n FROM electronica_boleta facturas INNER JOIN electronica_detalle_boleta detallefactura\r\n ON facturas.idBoleta = detallefactura.idBoletaLinea\r\n LEFT JOIN clientes\r\n ON clientes.codigo=facturas.idCliente \r\n WHERE " + filtro1 + " ORDER BY facturas.folio";
      ((DbCommand) command).CommandText = str5;
      ((DbDataAdapter)new MySqlDataAdapter(command)).Fill(boletaFacturaInformeDetalle);
      return boletaFacturaInformeDetalle;
    }

    public DataTable boletaFacturaInformeDetalleCategoriaProductos(string filtro)
    {
      string str1 = "SELECT  'FACTURA' as tipoDocumentoVenta, facturas.idFactura, facturas.folio, facturas.fechaEmision, facturas.fechaVencimiento, facturas.idCliente,  facturas.rut,  facturas.digito,  facturas.razonSocial, facturas.direccion,  facturas.comuna,  facturas.ciudad,  facturas.giro,  facturas.fono,  facturas.fax,  facturas.contacto,  facturas.diasPlazo,  facturas.idMedioPago, facturas.medioPago,  facturas.idVendedor,  facturas.vendedor,  facturas.idCentroCosto,  facturas.centroCosto,  facturas.ordenCompra,  facturas.subtotal,  facturas.porcentajeDescuento, facturas.descuento,  facturas.porcentajeIva,  facturas.iva, facturas.neto,  facturas.total,  facturas.totalPalabras,  facturas.estadoPago,  facturas.estadoDocumento,  facturas.impuesto1, facturas.impuesto2, facturas.impuesto3, facturas.impuesto4, facturas.impuesto5, facturas.porcentajeImpuesto1, facturas.porcentajeImpuesto2, facturas.porcentajeImpuesto3, facturas.porcentajeImpuesto4, facturas.porcentajeImpuesto5, detallefactura.idFacturaLinea, detallefactura.folioFactura, detallefactura.fechaIngreso, detallefactura.codigo, detallefactura.descripcion, detallefactura.valorVenta, detallefactura.cantidad, detallefactura.porcentajeDescuentoLinea, detallefactura.descuentoLinea, detallefactura.subtotalLinea,  detallefactura.totalLinea,  detallefactura.tipoDescuento,  detallefactura.listaPrecio,  detallefactura.bodega,  detallefactura.idDetallefactura, detallefactura.idImpuesto,  detallefactura.netoLinea, detallefactura.valorCompra, productos.Categoria as 'DescCategoria', productos.IdSubCategoria, productos.SubCategoria, productos.Marca\r\n FROM facturas \r\n INNER JOIN detallefactura ON facturas.idFactura = detallefactura.idFacturaLinea\r\n LEFT JOIN productos ON detallefactura.codigo=productos.Codigo \r\n WHERE " + filtro + " ORDER BY facturas.folio";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT  'BOLETA' as tipoDocumentoVenta, boletas.idBoleta, boletas.folio, boletas.fechaEmision, boletas.fechaVencimiento, boletas.dia, boletas.mes, boletas.ano, boletas.idCliente,  boletas.rut,  boletas.digito,  boletas.razonSocial, boletas.direccion,  boletas.comuna,  boletas.ciudad,  boletas.giro,  boletas.fono,  boletas.fax,  boletas.contacto,  boletas.diasPlazo,  boletas.idMedioPago, boletas.medioPago,  boletas.idVendedor,  boletas.vendedor,  boletas.idCentroCosto,  boletas.centroCosto,  boletas.ordenCompra,  boletas.subtotal,  boletas.porcentajeDescuento, boletas.descuento,  boletas.porcentajeIva,  boletas.iva, boletas.neto,  boletas.total,  boletas.totalExento, boletas.totalaCobrar, boletas.totalPalabras,  boletas.estadoPago,  boletas.estadoDocumento, boletas.totalPagado, boletas.totalDocumentado, boletas.totalPendiente, boletas.pagaCon, boletas.vuelto,    boletas.impuesto1, boletas.impuesto2, boletas.impuesto3, boletas.impuesto4, boletas.impuesto5, boletas.porcentajeImpuesto1, boletas.porcentajeImpuesto2, boletas.porcentajeImpuesto3, boletas.porcentajeImpuesto4, boletas.porcentajeImpuesto5, boletas.comisionVendedor, boletas.idTicket, boletas.folioTicket, boletas.caja, boletas.idCotizacion, boletas.folioCotizacion, detalleboleta.idDetalleboleta,    detalleboleta.idBoletaLinea, detalleboleta.folioBoleta, detalleboleta.fechaIngreso, detalleboleta.codigo, detalleboleta.descripcion, detalleboleta.valorVenta, detalleboleta.cantidad, detalleboleta.porcentajeDescuentoLinea, detalleboleta.descuentoLinea, detalleboleta.subtotalLinea,  detalleboleta.totalLinea,  detalleboleta.tipoDescuento,  detalleboleta.listaPrecio,  detalleboleta.bodega,  detalleboleta.exento,  detalleboleta.idImpuesto,  detalleboleta.netoLinea, detalleboleta.valorCompra, productos.Categoria as 'DescCategoria', productos.IdSubCategoria, productos.SubCategoria, productos.Marca\r\n    FROM boletas \r\n    INNER JOIN detalleboleta ON boletas.idBoleta = detalleboleta.idBoletaLinea\r\n    LEFT JOIN productos ON detalleboleta.codigo=productos.Codigo     \r\n    WHERE " + filtro + " ORDER BY folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str3 = "SELECT  'BOLETA FISCAL' as tipoDocumentoVenta, boletasfiscal.idBoleta, boletasfiscal.folio, boletasfiscal.fechaEmision, boletasfiscal.fechaVencimiento, boletasfiscal.dia, boletasfiscal.mes, boletasfiscal.ano, boletasfiscal.idCliente,  boletasfiscal.rut,  boletasfiscal.digito,  boletasfiscal.razonSocial, boletasfiscal.direccion,  boletasfiscal.comuna,  boletasfiscal.ciudad,  boletasfiscal.giro,  boletasfiscal.fono,  boletasfiscal.fax,  boletasfiscal.contacto,  boletasfiscal.diasPlazo,  boletasfiscal.idMedioPago, boletasfiscal.medioPago,  boletasfiscal.idVendedor,  boletasfiscal.vendedor,  boletasfiscal.idCentroCosto,  boletasfiscal.centroCosto,  boletasfiscal.ordenCompra,  boletasfiscal.subtotal,  boletasfiscal.porcentajeDescuento, boletasfiscal.descuento,  boletasfiscal.porcentajeIva,  boletasfiscal.iva, boletasfiscal.neto,  boletasfiscal.total,  boletasfiscal.totalExento, boletasfiscal.totalaCobrar, boletasfiscal.totalPalabras,  boletasfiscal.estadoPago,  boletasfiscal.estadoDocumento, boletasfiscal.totalPagado, boletasfiscal.totalDocumentado, boletasfiscal.totalPendiente, boletasfiscal.pagaCon, boletasfiscal.vuelto,    boletasfiscal.impuesto1, boletasfiscal.impuesto2, boletasfiscal.impuesto3, boletasfiscal.impuesto4, boletasfiscal.impuesto5, boletasfiscal.porcentajeImpuesto1, boletasfiscal.porcentajeImpuesto2, boletasfiscal.porcentajeImpuesto3, boletasfiscal.porcentajeImpuesto4, boletasfiscal.porcentajeImpuesto5, boletasfiscal.comisionVendedor, boletasfiscal.idTicket, boletasfiscal.folioTicket, boletasfiscal.caja, boletasfiscal.idCotizacion, boletasfiscal.folioCotizacion, detalleboletafiscal.idDetalleboleta,    detalleboletafiscal.idBoletaLinea, detalleboletafiscal.folioBoleta, detalleboletafiscal.fechaIngreso, detalleboletafiscal.codigo, detalleboletafiscal.descripcion, detalleboletafiscal.valorVenta, detalleboletafiscal.cantidad, detalleboletafiscal.porcentajeDescuentoLinea, detalleboletafiscal.descuentoLinea, detalleboletafiscal.subtotalLinea,  detalleboletafiscal.totalLinea,  detalleboletafiscal.tipoDescuento,  detalleboletafiscal.listaPrecio,  detalleboletafiscal.bodega,  detalleboletafiscal.exento,  detalleboletafiscal.idImpuesto,  detalleboletafiscal.netoLinea, detalleboletafiscal.valorCompra, productos.Categoria as 'DescCategoria', productos.IdSubCategoria, productos.SubCategoria, productos.Marca\r\n    FROM boletasfiscal \r\n    INNER JOIN detalleboletafiscal ON boletasfiscal.idBoleta = detalleboletafiscal.idBoletaLinea\r\n    LEFT JOIN productos ON detalleboletafiscal.codigo=productos.Codigo    \r\n    WHERE " + filtro + " ORDER BY folio";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str4 = "SELECT  'FACTURA ELECTRONICA' as tipoDocumentoVenta, facturas.idFactura, facturas.folio, facturas.fechaEmision, facturas.fechaVencimiento, facturas.idCliente,  facturas.rut,  facturas.digito,  facturas.razonSocial, facturas.direccion,  facturas.comuna,  facturas.ciudad,  facturas.giro,  facturas.fono,  facturas.fax,  facturas.contacto,  facturas.diasPlazo,  facturas.idMedioPago, facturas.medioPago,  facturas.idVendedor,  facturas.vendedor,  facturas.idCentroCosto,  facturas.centroCosto,  facturas.ordenCompra,  facturas.subtotal,  facturas.porcentajeDescuento, facturas.descuento,  facturas.porcentajeIva,  facturas.iva, facturas.neto,  facturas.total,  facturas.totalPalabras,  facturas.estadoPago,  facturas.estadoDocumento,  facturas.impuesto1, facturas.impuesto2, facturas.impuesto3, facturas.impuesto4, facturas.impuesto5, facturas.porcentajeImpuesto1, facturas.porcentajeImpuesto2, facturas.porcentajeImpuesto3, facturas.porcentajeImpuesto4, facturas.porcentajeImpuesto5, detallefactura.idFacturaLinea, detallefactura.folioFactura, detallefactura.fechaIngreso, detallefactura.codigo, detallefactura.descripcion, detallefactura.valorVenta, detallefactura.cantidad, detallefactura.porcentajeDescuentoLinea, detallefactura.descuentoLinea, detallefactura.subtotalLinea,  detallefactura.totalLinea,  detallefactura.tipoDescuento,  detallefactura.listaPrecio,  detallefactura.bodega,  detallefactura.idDetallefactura, detallefactura.idImpuesto,  detallefactura.netoLinea, detallefactura.valorCompra, productos.Categoria as 'DescCategoria', productos.IdSubCategoria, productos.SubCategoria, productos.Marca\r\n FROM electronica_factura facturas\r\n INNER JOIN electronica_detalle_factura detallefactura ON facturas.idFactura = detallefactura.idFacturaLinea\r\n LEFT JOIN productos ON detallefactura.codigo=productos.Codigo \r\n WHERE " + filtro + " ORDER BY facturas.folio";
      ((DbCommand) command).CommandText = str4;  
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str5 = "SELECT  'BOLETA ELECTRONICA' as tipoDocumentoVenta, facturas.idBoleta, facturas.folio, facturas.fechaEmision, facturas.fechaVencimiento, facturas.idCliente,  facturas.rut,  facturas.digito,  facturas.razonSocial, facturas.direccion,  facturas.comuna,  facturas.ciudad,  facturas.giro,  facturas.fono,  facturas.fax,  facturas.contacto,  facturas.diasPlazo,  facturas.idMedioPago, facturas.medioPago,  facturas.idVendedor,  facturas.vendedor,  facturas.idCentroCosto,  facturas.centroCosto,  facturas.ordenCompra,  facturas.subtotal,  facturas.porcentajeDescuento, facturas.descuento,  facturas.porcentajeIva,  facturas.iva, facturas.neto,  facturas.total,  facturas.totalPalabras,  facturas.estadoPago,  facturas.estadoDocumento,  facturas.impuesto1, facturas.impuesto2, facturas.impuesto3, facturas.impuesto4, facturas.impuesto5, facturas.porcentajeImpuesto1, facturas.porcentajeImpuesto2, facturas.porcentajeImpuesto3, facturas.porcentajeImpuesto4, facturas.porcentajeImpuesto5, detallefactura.idBoletaLinea, detallefactura.folioBoleta, detallefactura.fechaIngreso, detallefactura.codigo, detallefactura.descripcion, detallefactura.valorVenta, detallefactura.cantidad, detallefactura.porcentajeDescuentoLinea, detallefactura.descuentoLinea, detallefactura.subtotalLinea,  detallefactura.totalLinea,  detallefactura.tipoDescuento,  detallefactura.listaPrecio,  detallefactura.bodega,  detallefactura.idDetalleBoleta, detallefactura.idImpuesto,  detallefactura.netoLinea, detallefactura.valorCompra, productos.Categoria as 'DescCategoria', productos.IdSubCategoria, productos.SubCategoria, productos.Marca\r\n FROM electronica_boleta facturas\r\n INNER JOIN electronica_detalle_boleta detallefactura ON facturas.idBoleta = detallefactura.idBoletaLinea\r\n LEFT JOIN productos ON detallefactura.codigo=productos.Codigo \r\n WHERE " + filtro + " ORDER BY facturas.folio";
      ((DbCommand) command).CommandText = str5;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }

    public DataTable libroVentasInforme(string filtro)
    {
      string str1 = "SELECT 'NOTA CREDITO' as tipoDocumentoVenta,idNotaCredito as 'idFactura', folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal * -1 as 'subtotal', porcentajeDescuento, descuento * -1 as 'descuento', porcentajeIva, iva * -1 as 'iva', neto * -1 as 'neto', total * -1 as 'total',   impuesto1 * -1 as 'impuesto1', impuesto2 * -1 as 'impuesto2', impuesto3 * -1 as 'impuesto3', impuesto4 * -1 as 'impuesto4', impuesto5 * -1 as 'impuesto5', caja    \r\n FROM notacredito \r\n WHERE " + filtro + " AND documento='FACTURA' ORDER BY folio";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT 'FACTURA' as tipoDocumentoVenta,  idFactura,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total,   impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, caja \r\n FROM facturas \r\n WHERE " + filtro + "  ORDER BY folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str3 = "SELECT 'FACTURA ELECTRONICA' as tipoDocumentoVenta,  idFactura,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total,   impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, caja \r\n FROM electronica_factura\r\n WHERE " + filtro + "  ORDER BY folio";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str4 = "SELECT 'NOTA CREDITO ELECTRONICA' as tipoDocumentoVenta,    idNotaCredito as 'idFactura', folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal * -1 as 'subtotal', porcentajeDescuento, descuento * -1 as 'descuento', porcentajeIva, iva * -1 as 'iva', neto * -1 as 'neto', total * -1 as 'total',   impuesto1 * -1 as 'impuesto1', impuesto2 * -1 as 'impuesto2', impuesto3 * -1 as 'impuesto3', impuesto4 * -1 as 'impuesto4', impuesto5 * -1 as 'impuesto5', caja    \r\n FROM electronica_nota_credito \r\n WHERE " + filtro + " ORDER BY folio";
      ((DbCommand) command).CommandText = str4;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str5 = "SELECT 'NOTA DEBITO ELECTRONICA' as tipoDocumentoVenta,  idNotaDebito as 'idFactura',  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total,   impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, caja \r\n FROM electronica_nota_debito\r\n WHERE " + filtro + "  ORDER BY folio";
      ((DbCommand) command).CommandText = str5;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }

    public DataTable libroVentasBoletaFiscalInforme(string filtro)
    {
      string str1 = "SELECT 'NOTA CREDITO' as tipoDocumentoVenta,    idNotaCredito as 'idFactura', folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal * -1 as 'subtotal', porcentajeDescuento, descuento * -1 as 'descuento', porcentajeIva, iva * -1 as 'iva', neto * -1 as 'neto', total * -1 as 'total',   impuesto1 * -1 as 'impuesto1', impuesto2 * -1 as 'impuesto2', impuesto3 * -1 as 'impuesto3', impuesto4 * -1 as 'impuesto4', impuesto5 * -1 as 'impuesto5', caja    \r\n FROM notacredito \r\n WHERE " + filtro + " AND documento='BOLETA FISCAL' ORDER BY folio ";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT 'BOLETA FISCAL' as tipoDocumentoVenta,  idBoleta,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total,   impuesto1, impuesto2, impuesto3, impuesto4, impuesto5, caja \r\n FROM boletasfiscal \r\n WHERE " + filtro + "  ORDER BY folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }

    public DataTable boletaFacturaNotaCreditoInforme(string filtro)
    {
      string str1 = "SELECT 'BOLETA' as tipoDocumentoVenta, '1' as codigoDocumento, folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente \r\n FROM boletas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND (estadoPago= 'PENDIENTE' OR estadoPago= 'DOCUMENTADO') ORDER BY folio";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT 'FACTURA' as tipoDocumentoVenta, '2' as codigoDocumento,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente     \r\n FROM facturas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND (estadoPago= 'PENDIENTE' OR estadoPago= 'DOCUMENTADO') ORDER BY folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str3 = "SELECT 'FACTURA ELECTRONICA' as tipoDocumentoVenta, '20' as codigoDocumento,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente     \r\n FROM electronica_factura\r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND (estadoPago= 'PENDIENTE' OR estadoPago= 'DOCUMENTADO') ORDER BY folio";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str4 = "SELECT 'FACTURA EXENTA' as tipoDocumentoVenta, '3' as codigoDocumento,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente   \r\n FROM facturasexentas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND (estadoPago= 'PENDIENTE' OR estadoPago= 'DOCUMENTADO') ORDER BY folio";
      ((DbCommand) command).CommandText = str4;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str5 = "SELECT 'FACTURA EXENTA ELECTRONICA' as tipoDocumentoVenta, '30' as codigoDocumento,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente   \r\n FROM electronica_factura_exenta\r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND (estadoPago= 'PENDIENTE' OR estadoPago= 'DOCUMENTADO') ORDER BY folio";
      ((DbCommand) command).CommandText = str5;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str6 = "SELECT 'GUIAS SIN FACTURAR' as tipoDocumentoVenta, '4' as codigoDocumento,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,  total, total as 'totalPendiente',   estadoPago, estadoDocumento, 0 AS totalPagado, totalDocumentado     \r\n FROM guias \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND facturada=0 ORDER BY folio";
      ((DbCommand) command).CommandText = str6;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str7 = "SELECT 'GUIAS ELECTRONICAS SIN FACTURAR' as tipoDocumentoVenta, '40' as codigoDocumento,  folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,  total, total as 'totalPendiente',   estadoPago, estadoDocumento, 0 AS totalPagado, totalDocumentado     \r\n FROM electronica_guia\r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND facturada=0 AND (codigoTipoGuia=1 OR codigoTipoGuia=2 OR codigoTipoGuia=9 )\r\n ORDER BY folio";
      ((DbCommand) command).CommandText = str7;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str8 = "SELECT 'NOTA DE CREDITO' as tipoDocumentoVenta, '5' as codigoDocumento, folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, totalPagado, totalDocumentado, totalPendiente,   idTipo, tipoNotaCredito, montoUsado, (total-montoUsado) AS 'montoDisponible'   FROM notacredito    WHERE " + filtro + " AND estadoDocumento='EMITIDA' AND (idTipo=1 OR idTipo=3) AND total > montoUsado";
      ((DbCommand) command).CommandText = str8;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str9 = "SELECT 'NOTA DE CREDITO ELECTRONICA' as tipoDocumentoVenta, '50' as codigoDocumento, folio, fechaEmision, fechaVencimiento, idCliente, rut, digito, razonSocial,   total,   estadoPago, estadoDocumento, 0 as totalPagado, 0 as totalDocumentado, 0 as totalPendiente,    montoUsado, (total-montoUsado) AS 'montoDisponible'   FROM electronica_nota_credito    WHERE " + filtro + " AND  estadoDocumento='EMITIDA' AND  ((tipoAccion1=1 OR tipoAccion1=3) OR (tipoAccion2=1 OR tipoAccion2=3) OR (tipoAccion3=1 OR tipoAccion3=3) OR (tipoAccion4=1 OR tipoAccion4=3) OR (tipoAccion5=1 OR tipoAccion5=3)) AND total > montoUsado";
      ((DbCommand) command).CommandText = str9;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }

    public DataTable resumenVentaInforme(string filtro)
    {
      string str1 = "SELECT 'BOLETA' as tipoDocumentoVenta, '1' as codigoDocumento,  folio, fechaEmision,   idVendedor, vendedor,   subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total, caja      \r\n FROM boletas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      DataTable dataTable = new DataTable();
      MySqlCommand command = this.conexion.ConexionMySql.CreateCommand();
      ((DbCommand) command).CommandText = str1;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str2 = "SELECT 'FACTURA' as tipoDocumentoVenta, '2' as codigoDocumento,     folio, fechaEmision,   idVendedor, vendedor,   subtotal, porcentajeDescuento, descuento, porcentajeIva, iva, neto, total, caja     \r\n FROM facturas \r\n WHERE " + filtro + " AND estadoDocumento='EMITIDA' ORDER BY folio";
      ((DbCommand) command).CommandText = str2;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      string str3 = "SELECT 'NOTA DE CREDITO' as tipoDocumentoVenta, '3' as codigoDocumento, folio, fechaEmision,  idVendedor, vendedor,  subtotal,  porcentajeDescuento, descuento,  porcentajeIva,  iva,  neto,  total, caja,   idTipo, tipoNotaCredito, montoUsado, (total-montoUsado) AS 'montoDisponible'   FROM notacredito    WHERE " + filtro + " AND estadoDocumento='EMITIDA'";
      ((DbCommand) command).CommandText = str3;
      ((DbDataAdapter) new MySqlDataAdapter(command)).Fill(dataTable);
      return dataTable;
    }
  }
}
